version: "2"
services:
  bookstack:
    image: docker.io/linuxserver/bookstack
    container_name: bookstack
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_DATABASE=${MYSQL_DATABASE}
      - APP_URL="https://wiki.nelyah.eu"
    ports:
      - 6875:80
    volumes:
      - bookstack_data:/config
      - certificates:/etc/letsencrypt:ro
    restart: unless-stopped
    depends_on:
      - bookstack_db
    networks:
      - bookstack

  bookstack_db:
    image: docker.io/linuxserver/mariadb
    container_name: bookstack_db
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIME_ZONE}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - bookstack_db:/config/
    restart: unless-stopped
    networks:
      - bookstack

networks:
  bookstack:
    external: true

volumes:
  bookstack_db:
    external: true
  bookstack_data:
    external: true
  certificates:
    external: true
