---

- name: Setup ssh server
  import_tasks: ssh_server.yml

- name: Setup ssh
  import_tasks: ssh.yml

- name: Setup Syncthing
  import_tasks: syncthing.yml

- name: Setup the cronjobs
  import_tasks: cron.yml

- name: Setup the hard drives
  import_tasks: hard_drives.yml
