---

- name: Do Navidrome backup
  tags:
    - backup
  include_role:
    name: restic
    tasks_from: backup
  vars:
    restic_backup_data:
      path:
      volumes:
        - navidrome_data
        - navidrome_mum_data
      tags:
        - navidrome
      ignore_patterns:
      docker_data_dir: '{{ docker_data_dir }}'

- name: Prune Navidrome snapshots
  include_role:
    name: restic
    tasks_from: forget
  vars:
    restic_forget_data:
      tags_intersect:
      tags_union:
        - navidrome
      keep_daily: 10
      keep_weekly: 4
      prune: true

# vi:ft=yaml.ansible
