---

- name: Create required docker networks
  community.docker.docker_network:
    name: navidrome

- name: Create required docker volumes
  community.docker.docker_volume:
    name: '{{ docker_volumes }}'
  loop:
    - navidrome_data
    - navidrome_mum_data
  loop_control:
    loop_var: docker_volumes

- name: Deploy docker env file
  template:
    src: env
    dest: '{{ homeserver_repo_dir }}/services/navidrome/.env'

# vi:ft=yaml.ansible
