---
version: '3'

networks:
  authelia:
    external: true

volumes:
  authelia_config:
    external: true
  authelia_redis_data:
    external: true

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    stop_grace_period: 1m
    volumes:
      - authelia_config:/config
    networks:
      - authelia
    restart: unless-stopped
    healthcheck:
      ## In production the healthcheck section should be commented.
      disable: true
    environment:
      - TZ=Europe/Paris
    depends_on: 
      - redis

  redis:
    image: redis:latest
    container_name: authelia_redis
    stop_grace_period: 1m
    volumes:
      - authelia_redis_data:/data
    networks:
      - authelia
    restart: unless-stopped
    command:
      # Every 60s, write to database if at least 1 entry was given
      - --save 60 1
