version: '3'
services:
  unifi-controller:
    image: docker.io/linuxserver/unifi-controller
    container_name: unifi-controller
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
