---

- name: Create required docker networks
  community.docker.docker_network:
    name: emby

- name: Create required docker volumes
  community.docker.docker_volume:
    name: '{{ docker_volumes }}'
  loop:
    - emby_data
  loop_control:
    loop_var: docker_volumes

# vi:ft=yaml.ansible
