version: "2.3"
services:
  emby:
    image: emby/embyserver
    container_name: emby
    # network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=1002 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - emby_data:/config
      - /data/Movies:/mnt/share1
      - /data/TvShows:/mnt/share2
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    networks:
      - emby
    restart: unless-stopped

networks:
  emby:
    external: true

volumes:
  emby_data:
    external: true
