version: '3'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    stop_grace_period: 1m
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
    restart: unless-stopped
    networks:
      - grafana

  loki:
    image: grafana/loki:latest
    container_name: loki
    stop_grace_period: 1m
    command: -config.file=/etc/loki/loki_config.yml
    volumes:
      - ./loki_config.yml:/etc/loki/loki_config.yml:ro
    restart: unless-stopped
    networks:
      - grafana

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    stop_grace_period: 1m
    command: -config.file=/etc/promtail/promtail_config.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail_config.yml:/etc/promtail/promtail_config.yml:ro
      - /var/log:/var/log:ro
    restart: unless-stopped
    networks:
      - grafana

volumes:
  grafana_data:
    external: true

networks:
  grafana:
    external: true
