version: '3'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    stop_grace_period: 1m
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
    restart: unless-stopped
    networks:
      - grafana

volumes:
  grafana_data:
    external: true

networks:
  grafana:
    external: true
