version: '3.1'

services:
  mariadb-wp:
    container_name: mariadb-wp
    image: docker.io/mariadb
    restart: unless-stopped
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - wordpress


  wordpress:
    container_name: wordpress
    image: docker.io/wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
    volumes: 
      - wordpress_site:/var/www/html/
      - ./apache-config:/etc/apache2
      - certificates:/etc/letsencrypt:ro
    networks:
      - wordpress

volumes:
  wordpress_db:
    external: true
  wordpress_site:
    external: true
  certificates:
    external: true

networks:
  wordpress:
    external: true
