version: '3.1'

services:
  mariadb-wp:
    container_name: mariadb-wp
    image: docker.io/mariadb
    stop_grace_period: 1m
    restart: unless-stopped
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      - MARIADB_AUTO_UPGRADE="1"
      - MARIADB_INITDB_SKIP_TZINFO="1"
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - wordpress


  wordpress:
    container_name: wordpress
    image: docker.io/wordpress
    stop_grace_period: 1m
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_HOST=mariadb-wp
    volumes: 
      - wordpress_site:/var/www/html/
      - ./apache-config:/etc/apache2
      - certificates:/etc/letsencrypt:ro
    networks:
      - wordpress

volumes:
  wordpress_db:
    external: true
  wordpress_site:
    external: true
  certificates:
    external: true

networks:
  wordpress:
    external: true
