version: "3.7"

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    stop_grace_period: 1m
    restart: unless-stopped
    networks:
      - audiobookshelf
    volumes:
      - ${AUDIOBOOK_LIBRARY}:/audiobooks
      - audiobookshelf_db:/config
      - audiobookshelf_metadata:/metadata

networks:
  audiobookshelf:
    external: true

volumes:
  audiobookshelf_db:
    external: true
  audiobookshelf_metadata:
    external: true

