device:
  resourceName: nelyah.eu/thread
  id: 309eb9d5308aef118ae6c2a3ef8776e9
  hostPath: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_309eb9d5308aef118ae6c2a3ef8776e9-if00-port0
  healthPath: /host-dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_309eb9d5308aef118ae6c2a3ef8776e9-if00-port0
  containerPath: /dev/thread
  socketName: nelyah-thread.sock
  lockName: nelyah-thread.lock
