#! /bin/bash

cd $(dirname $(readlink -f $0))

[ -f .cache_my_address ] && OLD_PUB_IP=$(cat .cache_my_address) || OLD_PUB_IP=""
CUR_PUB_IP=$(curl ifconfig.me 2> /dev/null)

if [ -z "${OLD_PUB_IP}" ] || [ "${OLD_PUB_IP}" != "${CUR_PUB_IP}" ]; then

    compose_file=$(dirname $(readlink -f $0))/docker-compose.yml

    [ ! -e "${compose_file}" ] && "Error: no such file: ${compose_file}" && exit 1

    services=( ddclient_domain1 ddclient_domain2 )

    for service in ${services[@]}; do
        docker-compose -f "${compose_file}" run "${service}"
    done
    
    echo "${CUR_PUB_IP}" >  .cache_my_address
fi
