---

- hosts: localhost
  connection: local

  roles:
    - role: common
      become: yes

    - role: server
      become: yes

    - role: docker
      tags:
        - docker

  tasks:
    - name: Setup backup services
      become: true
      import_role:
        name: backup
        tasks_from: setup_services

