---

- name: Create required docker networks
  community.docker.docker_network:
    name: grafana

- name: Create required docker volumes
  community.docker.docker_volume:
    name: '{{ docker_volumes }}'
  loop:
    - grafana_data
  loop_control:
    loop_var: docker_volumes

- name: Install the Grafana config file
  template:
    src: grafana.ini.j2
    dest: '{{ homeserver_repo_dir }}/services/grafana/grafana.ini'

# vi:ft=yaml.ansible
