services:
  atuin:
    restart: always
    image: ghcr.io/atuinsh/atuin:latest
    container_name: atuin
    command: server start
    volumes:
      - "atuin_config:/config"
    links:
      - atuin_db:db
    networks:
      - frontend
      - backend
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "false"
      ATUIN_DB_URI: db://$ATUIN_DB_USERNAME:$ATUIN_DB_PASSWORD@db/$ATUIN_DB_NAME
      RUST_LOG: info,atuin_server=debug
  atuin_db:
    image: postgres:14
    container_name: atuin_db
    restart: unless-stopped
    networks:
      - frontend
      - backend
    volumes:
      - "atuin_db:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: ${ATUIN_DB_NAME}

networks:
  frontend:
    external: true
  backend:
    external: true

volumes:
  atuin_db:
    external: true
  atuin_config:
    external: true
