{{- $namespace := required "app.name is required" (default .Values.app.name .Values.app.namespace) -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: synapse-vault-auth
  namespace: {{ $namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: synapse-vault-auth-tokenreview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: synapse-vault-auth
    namespace: {{ $namespace }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: synapse
  namespace: {{ $namespace }}
spec:
  vaultAuthGlobalRef:
    name: homeserver
    namespace: vault-secrets-operator-system
  kubernetes:
    role: synapse
    serviceAccount: synapse-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: synapse
  namespace: {{ $namespace }}
spec:
  vaultAuthRef: synapse
  type: kv-v2
  mount: homeserver_secrets
  path: synapse
  refreshAfter: 1h
  hmacSecretData: true
  destination:
    create: true
    overwrite: true
    name: synapse
    transformation:
      includes:
        - "^POSTGRES_PASSWORD$"
        - "^REGISTRATION_SHARED_SECRET$"
  rolloutRestartTargets:
    - kind: Deployment
      name: synapse
    - kind: Deployment
      name: synapse-db
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: doublepuppet
  namespace: {{ $namespace }}
spec:
  vaultAuthRef: synapse
  type: kv-v2
  mount: homeserver_secrets
  path: doublepuppet
  refreshAfter: 1h
  hmacSecretData: true
  destination:
    create: true
    overwrite: true
    name: doublepuppet
    transformation:
      includes:
        - "^AS_TOKEN$"
        - "^HS_TOKEN$"
  rolloutRestartTargets:
    - kind: Deployment
      name: synapse
    - kind: Deployment
      name: mautrix-signal
    - kind: Deployment
      name: mautrix-whatsapp
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mautrix-signal
  namespace: {{ $namespace }}
spec:
  vaultAuthRef: synapse
  type: kv-v2
  mount: homeserver_secrets
  path: mautrix-signal
  refreshAfter: 1h
  hmacSecretData: true
  destination:
    create: true
    overwrite: true
    name: mautrix-signal
    transformation:
      includes:
        - "^AS_TOKEN$"
        - "^HS_TOKEN$"
        - "^POSTGRES_PASSWORD$"
        - "^PICKLE_KEY$"
        - "^PUBLIC_MEDIA_SIGNING_KEY$"
        - "^PROVISIONING_SECRET$"
  rolloutRestartTargets:
    - kind: Deployment
      name: synapse
    - kind: Deployment
      name: mautrix-signal
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mautrix-whatsapp
  namespace: {{ $namespace }}
spec:
  vaultAuthRef: synapse
  type: kv-v2
  mount: homeserver_secrets
  path: mautrix-whatsapp
  refreshAfter: 1h
  hmacSecretData: true
  destination:
    create: true
    overwrite: true
    name: mautrix-whatsapp
    transformation:
      includes:
        - "^AS_TOKEN$"
        - "^HS_TOKEN$"
        - "^POSTGRES_PASSWORD$"
        - "^PICKLE_KEY$"
        - "^PROVISIONING_SECRET$"
  rolloutRestartTargets:
    - kind: Deployment
      name: synapse
    - kind: Deployment
      name: mautrix-whatsapp
