version: '3.5'

services:
  photoprism_app:
    image: photoprism/photoprism:latest
    container_name: photoprism
    stop_grace_period: 1m
    depends_on:
      - photoprism_db
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    user: "1000:1000"
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}
      PHOTOPRISM_ORIGINALS_LIMIT: 5000                    # File size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: gzip                   # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "false"                           # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                          # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                        # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"                    # Enables experimental features
      PHOTOPRISM_DISABLE_WEBDAV: "false"                  # Disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"                # Disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"              # Disables using TensorFlow for image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "false"               # Enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_DETECT_NSFW: "false"                     # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                      # Allow uploads that MAY be offensive
      PHOTOPRISM_DATABASE_DRIVER: mysql                   # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_NAME: photoprism                # MariaDB database schema name
      PHOTOPRISM_DATABASE_USER: photoprism                # MariaDB database user name
      PHOTOPRISM_DATABASE_PASSWORD: ${MYSQL_PASSWORD}     # MariaDB database user password
      PHOTOPRISM_SITE_URL: https://photos.nelyah.eu       # Public PhotoPrism URL
      PHOTOPRISM_SITE_TITLE: PhotoPrism
      PHOTOPRISM_SITE_CAPTION: ""
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      HOME: "/photoprism"
      UID: 1000
      GID: 1000
      PHOTOPRISM_DATABASE_SERVER: "photoprism_db:3306"         # MariaDB database server (hostname:port)
    networks:
      - photoprism
    working_dir: "/photoprism"
    volumes:
      - "/data/pictures:/photoprism/originals"
      # Multiple folders can be indexed by mounting them as sub-folders of /photoprism/originals:
      - photoprism_data:/photoprism/storage

  photoprism_db:
    restart: unless-stopped
    image: mariadb:10.5
    stop_grace_period: 1m
    container_name: photoprism_db
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: >
      mysqld 
      --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci --max-connections=512
      --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes:
      - photoprism_db:/var/lib/mysql
    networks:
      - photoprism
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=photoprism
      - MYSQL_USER=photoprism
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  photoprism_data:
    external: true
  photoprism_db:
    external: true

networks:
  photoprism:
    external: true
