---

- name: Create required docker networks
  community.docker.docker_network:
    name: audiobookshelf

- name: Create required docker volumes
  community.docker.docker_volume:
    name: '{{ docker_volumes }}'
  loop:
    - audiobookshelf_db
    - audiobookshelf_metadata
  loop_control:
    loop_var: docker_volumes

- name: Deploy env file
  template:
    src: env.j2
    dest: '{{ homeserver_repo_dir }}/services/audiobookshelf/.env'

# vi:ft=yaml.ansible
