---

- name: Do Pihole backup
  tags:
    - backup
  include_role:
    name: restic
    tasks_from: backup
  vars:
    restic_backup_data:
      path:
      volumes:
        - pihole_config
        - pihole_dnsmasq_config
      tags:
        - pihole
      ignore_patterns:
      docker_data_dir: '{{ docker_data_dir }}'

- name: Prune Pihole snapshots
  include_role:
    name: restic
    tasks_from: forget
  vars:
    restic_forget_data:
      tags_intersect:
      tags_union:
        - pihole
      keep_daily: 10
      keep_weekly: 4
      keep_monthly: 4
      prune: true

# vi:ft=yaml.ansible
