---

# expect as available variables:
#
# restic_repos:
#   repo1:
#     password: secret_pass
#     path: /path/to/the/repo1
#     init: true
#   repo2:
#     password: secret_pass2
#     path: /path/to/the/repo2
#     init: true

- name: Init restic repository
  command: restic init
  environment:
    RESTIC_PASSWORD: '{{ item.value.password }}'
    RESTIC_REPOSITORY: '{{ item.value.path }}'
  no_log: True
  register: restic_init
  changed_when: "'created restic repository' in restic_init.stdout"
  failed_when:
    - restic_init.rc != 0
    - not 'config file already exists' in restic_init.stderr
    - not 'config already initialized' in restic_init.stderr
    - not 'config already exists' in restic_init.stderr
  loop: '{{ restic_repos | dict2items }}'
  when:
    - item.value.init is defined
    - item.value.init

# vi:ft=yaml.ansible
