---

- name: Initialise restic repositories
  import_role:
    name: restic
    tasks_from: init
  tags:
    - backup

- name: Do the backup
  include_role:
    name: '{{ backup_service }}'
    tasks_from: backup
    apply:
      tags:
        - '{{ backup_service }}'
  loop: '{{ backup_services }}'
  loop_control:
    loop_var: backup_service
  tags:
    - always

# vi:ft=yaml.ansible
