---

- name: Set facts
  set_fact:
    database: /tmp/wordpress_{{ansible_date_time.date | replace('-', '')}}.sql

- name: Do Wordpress backup
  block:
    - name: Enable maintenance mode
      command: >
        docker run --rm
        --volumes-from wordpress
        --network wordpress
        wordpress:cli maintenance-mode activate

    - name: Do Wordpress database dump
      shell: >
        docker run --rm \
        --volumes-from wordpress \
        --network wordpress \
        wordpress:cli sh -c "wp db export -" > "{{ database }}"

    - name: Perform backup with restic
      tags:
        - backup
      include_role:
        name: restic
        tasks_from: backup
      vars:
        restic_backup_data:
          path:
            - '{{ database }}'
          volumes:
            - wordpress_site
          tags:
            - wordpress
          ignore_patterns:
            - .opcache
            - .maintenance
            - access.log
            - error.log
          docker_data_dir: '{{ docker_data_dir }}'
  always:
    - name: Disable maintenance mode
      command: >
        docker run --rm
        --volumes-from wordpress
        --network wordpress
        wordpress:cli maintenance-mode deactivate

    - name: Remove database dump
      file:
        name: '{{ database }}'
        state: absent

- name: Prune Wordpress snapshots
  include_role:
    name: restic
    tasks_from: forget
  vars:
    restic_forget_data:
      tags_intersect:
      tags_union:
        - wordpress
      keep_daily: 10
      keep_weekly: 4
      prune: true

# vi:ft=yaml.ansible
