version: "3"
services:
  navidrome:
    image: docker.io/deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      user: 1000:1000
      ND_DEVACTIVITYPANEL: "true"
      ND_SCANINTERVAL: "744h"
      ND_PORT: 80
      ND_TRANSCODINGCACHESIZE: 100MB
      ND_SESSIONTIMEOUT: "744h"
    networks:
      - navidrome
    volumes:
      - ${MUSIC_FOLDER}:/music:ro
      - navidrome_data:/data/

volumes:
  navidrome_data:
    external: true

networks:
  navidrome:
    external: true
