apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name:  vault-secrets-operator
  namespace: kube-system
spec:
  repo: https://helm.releases.hashicorp.com
  chart: vault-secrets-operator
  targetNamespace: vault-secrets-operator-system
  createNamespace: true
  version: 1.4.0

