version: '3'

services:
  nginx_reverse-proxy:
    image: nginx_proxy
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    environment:
      - BLOG_URL_OLD=${BLOG_URL_OLD}
      - BLOG_URL_NEW=${BLOG_URL_NEW}
      - BLOG_INTERNAL_NAME=${BLOG_INTERNAL_NAME}
      - PIHOLE_INTERNAL_NAME=${PIHOLE_INTERNAL_NAME}
      - PIHOLE_URL=${PIHOLE_URL}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_INTERNAL_NAME=${INFLUXDB_INTERNAL_NAME}
      - CINEMA_INTERNAL_NAME=${CINEMA_INTERNAL_NAME}
      - CINEMA_URL=${CINEMA_URL}
      - CLOUD_INTERNAL_NAME=${CLOUD_INTERNAL_NAME}
      - CLOUD_URL=${CLOUD_URL}
      - WIKI_URL=${WIKI_URL}
      - WIKI_INTERNAL_NAME=${WIKI_INTERNAL_NAME}
      - MUSIC_URL=${MUSIC_URL}
      - MUSIC_INTERNAL_NAME=${MUSIC_INTERNAL_NAME}
      - PHOTOS_URL=${PHOTOS_URL}
      - PHOTOS_INTERNAL_NAME=${PHOTOS_INTERNAL_NAME}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - PROMETHEUS_INTERNAL_NAME=${PROMETHEUS_INTERNAL_NAME}
      - GRAFANA_URL=${GRAFANA_URL}
      - GRAFANA_INTERNAL_NAME=${GRAFANA_INTERNAL_NAME}
      - CERTIFICATE_NAME=${CERTIFICATE_NAME}
      - NGINX_ENVSUBST_OUTPUT_DIR=${NGINX_ENVSUBST_OUTPUT_DIR}
    volumes:
      - ./nginx_config:/etc/nginx/
      - certificates:/etc/letsencrypt:ro
    networks:
      - emby
      - grafana
      - influxdb
      - nextcloud
      - navidrome
      - photoprism
      - pihole
      - prometheus
      - bookstack
      - wordpress

volumes:
  certificates:
    external: true
  nginx_config:
    external: true

networks:
  nextcloud:
    external: true
  bookstack:
    external: true
  influxdb:
    external: true
  wordpress:
    external: true
  navidrome:
    external: true
  emby:
    external: true
  photoprism:
    external: true
  pihole:
    external: true
  prometheus:
    external: true
  grafana:
    external: true
