---

- name: Create required docker networks
  community.docker.docker_network:
    name: ghost

- name: Create required docker volumes
  community.docker.docker_volume:
    name: '{{ docker_volumes }}'
  loop:
    - ghost_data
    - ghost_db
  loop_control:
    loop_var: docker_volumes

- block:
  - name: Fetch secrets from vault
    community.hashi_vault.vault_kv2_get:
      url: '{{ vault.url }}'
      path: ghost
      engine_mount_point: homeserver_secrets
      auth_method: token
      token_path: '{{ homeserver_repo_dir }}/host/'
    register: response

  - name: Deploy docker env file
    template:
      src: env
      dest: '{{ homeserver_repo_dir }}/services/ghost/.env'

  - name: Deploy configuration for production
    template:
      src: config.production.json.j2
      dest: '{{ homeserver_repo_dir }}/services/ghost/config.production.json'

- name: Deploy ghost-autohealth script
  template:
    src: ghost-autohealth.sh.j2
    dest: /usr/bin/ghost-autohealth.sh
    mode: '0744'
    owner: root
    group: sudo

- name: Deploy systemd service
  template:
    src: ghost-autohealth.service
    dest: /etc/systemd/system/ghost-autohealth.service

- name: Deploy systemd timer
  template:
    src: ghost-autohealth.timer
    dest: /etc/systemd/system/ghost-autohealth.timer

- name: Start and enable autohealth timer
  systemd:
    daemon_reload: yes
    name: ghost-autohealth.timer
    state: started
    enabled: yes
# vi:ft=yaml.ansible
