version: '3'

services:
  mariadb-nc:
    container_name: mariadb-nc
    image: docker.io/mariadb
    restart: unless-stopped
    volumes:
      - nextcloud_mariadb:/var/lib/mysql
      - ./mariadb.conf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    networks:
      - nextcloud

  nextcloud-app:
    container_name: nextcloud
    image: docker.io/nextcloud:fpm
    depends_on: 
      - mariadb-nc
    restart: unless-stopped
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - NEXTCLOUD_DATA_DIR=${NC_DATA_DIR}
    volumes:
      - nextcloud_site:${NC_WEBSITE_DIR}
      - nextcloud_data:${NC_DATA_DIR}
      - certificates:/etc/letsencrypt:ro
    networks:
      - nextcloud

  cron:
    container_name: nextcloud-cron
    image: docker.io/nextcloud:fpm
    restart: unless-stopped
    volumes:
      - nextcloud_site:${NC_WEBSITE_DIR}
      - nextcloud_data:${NC_DATA_DIR}
    entrypoint: /cron.sh
    networks:
      - nextcloud

  web:
    container_name: nginx-nc
    image: docker.io/nginx
    restart: unless-stopped
    links:
      - nextcloud-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certificates:/etc/letsencrypt:ro
      - nextcloud_site:${NC_WEBSITE_DIR}
    networks:
      - nextcloud

volumes:
  nextcloud_data:
    external: true
  nextcloud_site:
    external: true
  certificates:
    external: true
  nextcloud_mariadb:
    external: true

networks:
  nextcloud:
    external: true
