---

- name: Create required docker networks
  community.docker.docker_network:
    name: nextcloud

- name: Create required docker volumes
  community.docker.docker_network:
    name: '{{ docker_volumes }}'
  loop:
    - nextcloud_data
    - nextcloud_site
  loop_control:
    loop_var: docker_volumes

# vi:ft=yaml.ansible
