version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    stop_grace_period: 1m
    volumes:
      - homepage_config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - homepage

networks:
  homepage:
    external: true

volumes:
  homepage_config:
    external: true
