{{- if .Values.secrets.enabled -}}

{{- $name := required "name is required" .Values.name -}}
{{- $vaultPath := required "vaultPath is required" .Values.secrets.vaultPath -}}
{{- $namespace := default .Values.name .Values.namespace -}}
{{- $role := $name -}}
{{- $mount := default "homeserver_secrets" .Values.secrets.mount -}}
{{- $secretName := $name -}}
{{- $serviceAccountName := printf "%s-vault-auth" $name  -}}
{{- $includeKeys := .Values.secrets.includeKeys | default (list) -}}
{{- if eq (len $includeKeys) 0 -}}
  {{- fail "includeKeys is required and must contain at least one key" -}}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ $namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-tokenreview" $serviceAccountName | trunc 63 | trimSuffix "-" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $namespace }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  vaultAuthGlobalRef:
    name: homeserver
    namespace: vault-secrets-operator-system
  kubernetes:
    role: {{ $role }}
    serviceAccount: {{ $serviceAccountName }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  vaultAuthRef: {{ $name }}
  type: kv-v2
  mount: {{ $mount }}
  path: {{ $vaultPath }}
  refreshAfter: 1h
  hmacSecretData: true
  destination:
    create: true
    overwrite: true
    name: {{ $secretName }}
    transformation:
      includes:
{{- range $includeKeys }}
        - {{ printf "^%s$" (regexQuoteMeta .) | quote }}
{{- end }}
{{- with .Values.deployments }}
  rolloutRestartTargets:
{{- range . }}
    - kind: Deployment
      name: {{ .name }}
{{- end }}
{{- end }}

{{- end }}
