apiVersion: v1
kind: PersistentVolume
metadata:
  name: photo-library
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/pictures
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - home-stockholm
