- name: Create required docker networks
  community.docker.docker_network:
    name: nextcloud

- name: Create required docker volumes
  community.docker.docker_volume:
    name: '{{ docker_volumes }}'
  loop:
    - nextcloud_data
    - nextcloud_site
    - nextcloud_redis_data
  loop_control:
    loop_var: docker_volumes

- name: Deploy systemd service
  template:
    src: nextcloud-index-update.service
    dest: /etc/systemd/system/nextcloud-index-update.service

- name: Deploy systemd timer
  template:
    src: nextcloud-index-update.timer
    dest: /etc/systemd/system/nextcloud-index-update.timer

- name: Start and enable autohealth timer
  systemd:
    daemon_reload: yes
    name: nextcloud-index-update.timer
    state: started
    enabled: yes

- block:
  - name: Read values from vault
    community.hashi_vault.vault_kv2_get:
      url: '{{ vault.url }}'
      path: nextcloud
      engine_mount_point: homeserver_secrets
      auth_method: token
      token_path: '{{ homeserver_repo_dir }}/host/'
    register: response

  - name: Deploy docker env file
    template:
      src: env
      dest: '{{ homeserver_repo_dir }}/services/nextcloud/.env'

# vi:ft=yaml.ansible
