---

- name: Set facts
  set_fact:
    # Do not set the date in the database name. If restic gets a file with a different
    # name as argument input, it will re-read everything
    # https://forum.restic.net/t/restic-never-finds-a-parent-snapshot/3938/4
    database: /tmp/wordpress_db.sql

- name: Do Wordpress backup
  block:
    - name: Enable maintenance mode
      command: >
        docker run --rm
        --volumes-from wordpress
        --network wordpress
        wordpress:cli maintenance-mode activate

    - name: Do Wordpress database dump
      shell: >
        docker run --rm \
        --volumes-from wordpress \
        --network wordpress \
        wordpress:cli sh -c "wp db export -" > "{{ database }}"

    - name: Perform backup with restic
      tags:
        - backup
      include_role:
        name: restic
        tasks_from: backup
      vars:
        restic_backup_data:
          path:
            - '{{ database }}'
          volumes:
            - wordpress_site
            - wordpress_db
          tags:
            - wordpress
          ignore_patterns:
            - .opcache
            - .maintenance
            - access.log
            - error.log
          docker_data_dir: '{{ docker_data_dir }}'
  always:
    - name: Disable maintenance mode
      command: >
        docker run --rm
        --volumes-from wordpress
        --network wordpress
        wordpress:cli maintenance-mode deactivate

    - name: Remove database dump
      file:
        name: '{{ database }}'
        state: absent

- name: Prune Wordpress snapshots
  include_role:
    name: restic
    tasks_from: forget
  vars:
    restic_forget_data:
      tags_intersect:
      tags_union:
        - wordpress
      keep_daily: 10
      keep_weekly: 4
      prune: true

# vi:ft=yaml.ansible
