---

- name: Create required docker networks
  community.docker.docker_network:
    name: wordpress

- name: Create required docker volumes
  community.docker.docker_volume:
    name: '{{ docker_volumes }}'
  loop:
    - wordpress_db
    - wordpress_site
  loop_control:
    loop_var: docker_volumes

- block:
  - name: Read values from vault
    community.hashi_vault.vault_kv2_get:
      url: '{{ vault.url }}'
      path: wordpress
      engine_mount_point: homeserver_secrets
      auth_method: token
      token_path: '{{ homeserver_repo_dir }}/host/'
    register: response

  - name: Deploy docker env file
    template:
      src: env
      dest: '{{ homeserver_repo_dir }}/services/wordpress/.env'

# vi:ft=yaml.ansible
