version: "3.1"
services:
  ghost:
    image: ghost:alpine
    container_name: ghost
    restart: unless-stopped
    depends_on: 
      - db
    networks:
      - ghost
    volumes:
      # The configuration file is setup by ansible because it contains secrets
      - ./config.production.json:/var/lib/ghost/config.production.json
      - ghost_data:/var/lib/ghost/content
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${MYSQL_ROOT_PASSWORD}
      database__connection__database: ghost
      url: https://ghost.nelyah.eu
      # Default is production mode, can also be 'development'
      NODE_ENV: production

  db:
    image: mysql:8.0
    container_name: ghost_db
    restart: unless-stopped
    volumes:
      - ghost_db:/var/lib/mysql
    networks:
      - ghost
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

volumes:
  ghost_data:
    external: true
  ghost_db:
    external: true

networks:
  ghost:
    external: true
