version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    stop_grace_period: 1m
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb2:rw
    networks:
      - grafana
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME=${DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME}

volumes:
  influxdb_data:
    external: true

networks:
  grafana:
    external: true
