---

- name: Install fail2ban package
  package:
    name:
      - fail2ban
    state: present
    update_cache: true

- name: Define fail2ban variables
  set_fact:
    fail2ban_ssh_ports:
      - '{{ssh_server_port}}'

- name: Apply fail2ban common config
  template:
    src: fail2ban.conf.j2
    dest: '/etc/fail2ban/jail.d/homeserver-common.conf'
  notify: 'reload fail2ban'

- name: Start and enable fail2ban systemd service
  systemd:
    name: fail2ban
    state: started
    enabled: yes
