---

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Add appropriate repos
  import_tasks: 'repos.yml'

- name: Install required packages
  import_tasks: 'packages.yml'

- name: Setup fail2ban
  tags:
    - fail2ban
  import_tasks: 'fail2ban.yml'

- name: Set users
  import_tasks: 'users.yml'

- name: Allow all access to tcp port 80
  tags:
    - firewall
  block:
    - name: Enable and start the ufw systemd service
      systemd:
        daemon_reload: yes
        name: ufw
        state: started
        enabled: yes

    - name: Set rules to open ports
      community.general.ufw:
        rule: allow
        port: '{{ item }}'
        proto: any
      loop: '{{ firewall.open_ports }}'

    - name: Enable ufw
      community.general.ufw:
        state: enabled

- name: Deploy system-wide environment configuration
  copy:
    src: etc-environment
    dest: '/etc/environment'
    mode: '600'

- name: Deploy environment configuration for users
  template:
    src: homeserver_config.sh.j2
    dest: '/etc/profile.d/homeserver_config.sh'
    owner: 'root'
    group: 'root'
    mode: '0644'
