---

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Add appropriate repos
  import_tasks: 'repos.yml'

- name: Install required packages
  import_tasks: 'packages.yml'

- name: Setup fail2ban
  import_tasks: 'fail2ban.yml'

- name: Set users
  import_tasks: 'users.yml'

- name: Deploy system-wide environment configuration
  copy:
    src: etc-environment
    dest: '/etc/environment'
    mode: '600'

- name: Deploy environment configuration for users
  template:
    src: homeserver_config.sh.j2
    dest: '/etc/profile.d/homeserver_config.sh'
    owner: 'root'
    group: 'root'
    mode: '0644'
