---

- name: Tailscale APT repo
  tags:
    - tailscale
  block:
    - name: Download tailscale apt key
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/debian/{{ ansible_distribution_release }}.noarmor.gpg
        dest: /etc/apt/keyrings/tailscale.gpg

    - name: Add tailscale apt repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/tailscale.gpg] https://pkgs.tailscale.com/stable/debian {{ ansible_distribution_release }} main"
        state: present
