---

- name: determine available groups
  getent:
    database: group

- name: Add the missing groups
  group:
    name: '{{ item }}'
    state: present
  loop: '{{ users | map(attribute="groups") | flatten }}'

- name: Set users
  no_log: true
  loop: '{{ users }}'
  user:
    name: '{{ item.login }}'
    comment: '{{ item.full_name }}'
    password: '{{ item.password | password_hash("sha512") }}'
    groups: '{{ item.groups | join(",") }}{{ ",wheel" if item.can_sudo else "" }}'
    shell: '{{ item.shell | default("/bin/bash") }}'
    update_password: on_create

- name: Remove inactive users
  no_log: true
  user:
    name: '{{ item.login }}'
    state: absent
    remove: no
  loop: '{{ users }}'
  when: 'item.active is defined and not item.active'

# vi:ft=yaml.ansible
