---

- name: determine available groups
  getent:
    database: group

- name: Add the missing groups
  group:
    name: '{{ item }}'
    state: present
  loop: '{{ users | map(attribute="groups") | flatten + ["sudo"] }}'

- name: Set users
  user:
    name: '{{ item.login }}'
    groups: '{{ item.groups | join(",") }}{{ ",sudo" if item.can_sudo else "" }}'
    shell: '{{ item.shell | default("/bin/bash") }}'
    update_password: on_create
  loop: '{{ users }}'
  when:
    - 'item.active is not defined or item.active'

- name: Remove inactive users
  no_log: true
  user:
    name: '{{ item.login }}'
    state: absent
    remove: no
  loop: '{{ users }}'
  when: 'item.active is defined and not item.active'

- name: Create ssh directory for root
  file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Create ssh directory for users
  no_log: true
  file:
    path: '/home/{{ item.login }}/.ssh'
    state: directory
    owner: '{{ item.login }}'
    group: '{{ item.login }}'
    mode: '0700'
  loop: '{{ users }}'
  when:
    - 'item.active is defined and item.active'

# vi:ft=yaml.ansible
