---

- name: determine available groups
  getent:
    database: group

- name: Add the missing groups
  group:
    name: '{{ item }}'
    state: present
  loop: '{{ users | map(attribute="groups") | flatten }}'

- name: Set users
  no_log: true
  loop: '{{ users }}'
  user:
    name: '{{ item.login }}'
    comment: '{{ item.full_name }}'
    password: '{{ item.password | password_hash("sha512") }}'
    groups: '{{ item.groups | join(",") }}{{ ",wheel" if item.can_sudo else "" }}'
    shell: '{{ item.shell | default("/bin/bash") }}'
    update_password: on_create

- name: Remove inactive users
  no_log: true
  user:
    name: '{{ item.login }}'
    state: absent
    remove: no
  loop: '{{ users }}'
  when: 'item.active is defined and not item.active'

- name: Create ssh directory for root
  file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Deploy ssh config for root
  copy:
    src: ssh_config
    dest: /root/.ssh/config
    mode: '0600'

- name: Create ssh directory for users
  file:
    path: '/home/{{ item }}/.ssh'
    state: directory
    owner: '{{ item }}'
    group: '{{ item }}'
    mode: '0700'
  loop: '{{ users | selectattr("ssh_config") | map(attribute="login") | list }}'
  when: 'item.active is not defined or item.active'

- name: Deploy ssh config for users
  copy:
    src: ssh_config
    dest: /home/{{ item }}/.ssh/config
    owner: '{{ item }}'
    group: '{{ item }}'
    mode: '0600'
  loop: '{{ users | selectattr("ssh_config") | map(attribute="login") | list }}'
  when: 'item.active is not defined or item.active'

# vi:ft=yaml.ansible
