version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    stop_grace_period: 1m
    volumes:
      - ./prometheus_config.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - prometheus

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
      - '--collector.systemd'
    networks:
      - prometheus
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

  cadvisor:
    # TODO: latest tag is not updated, check latest release https://github.com/google/cadvisor/releases
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    stop_grace_period: 1m
    networks:
      - prometheus
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /data/docker-data/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - --housekeeping_interval=1m0s
      - --disable_metrics=disk
    devices:
      - /dev/kmsg
    restart: unless-stopped
    privileged: true

  smartctl_exporter:
    build: exporters
    container_name: smartctl_exporter
    stop_grace_period: 1m
    privileged: true
    restart: unless-stopped
    command:
      - --reload
      - --port
      - '8000'
    environment:
      SMART_DEVICES: /dev/sda:/dev/sdb:/dev/sdc
    networks:
      - prometheus
    volumes:
      - /dev:/dev:ro


volumes:
  prometheus_data:
    external: true
  prometheus_config:
    external: true

networks:
  prometheus:
    external: true
