version: "3"

services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    stop_grace_period: 1m
    restart: unless-stopped
    networks:
      - homebox
    volumes:
      - homebox_data:/data
    environment:
      TZ: Europe/Paris

volumes:
  homebox_data:
    external: true

networks:
  homebox:
    external: true
