- block:
  - name: Fetch secrets from vault
    community.hashi_vault.vault_kv2_get:
      url: '{{ vault.url }}'
      path: ovh_api
      engine_mount_point: homeserver_secrets
      auth_method: token
      token_path: '{{ homeserver_repo_dir }}/host/'
    register: response

  - name: Deploy docker env file
    template:
      src: env
      dest: '{{ homeserver_repo_dir }}/services/ovh_dyndns_updater/.env'

- name: Deploy systemd service
  template:
    src: ovh_dyndns_updater.service.j2
    dest: /etc/systemd/system/ovh_dyndns_updater.service

- name: Deploy systemd timer
  template:
    src: ovh_dyndns_updater.timer
    dest: /etc/systemd/system/ovh_dyndns_updater.timer

- name: Start and enable autohealth timer
  systemd:
    daemon_reload: yes
    name: ovh_dyndns_updater.timer
    state: started
    enabled: yes
# vi:ft=yaml.ansible
